### ISSUE TITLE
Issues when used alongside the Lock View module 

### ISSUE THREAD

**Issue by samgrieve** [sPOiDar/fvtt-module-stream-view#10]
I use the Lock View module to fill the screen for my players when I am in non-combat/exploration scenes. For example if they visit a merchant I usually have a background image of the store to set the mood. If i have the Stream View module enabled my Observer window displays half of the scene cut off.

There are two screenshots below, one with Lock View enabled and Stream View disabled, the second with both enabled.

I understand this is probably a really small usecase not effecting many users but would be cool to find a way to use both. Perhaps on scenes with no tokens present StreamView could not attempt to control the zoom/pan of the canvas?

![nostreamview](https://user-images.githubusercontent.com/22322830/137633650-2ebcf128-074d-4a02-be45-7fd60bb96cde.PNG)

![streamview](https://user-images.githubusercontent.com/22322830/137633658-de5552ba-6f9c-46a7-becd-e51bcf8bd545.PNG)

**Comment by sPOiDar** [comment]
Currently if there are no tokens on a scene, Stream View will just use the current scene position and scale as reported by the canvas, when calculating the focus. I guess this doesn't interact well with Lock View somehow though, solving this may need some specific handling for compatibility with that module, if it's enabled. I'll try to find some time to dig into how the interaction works.

**Comment by sPOiDar** [comment]
This should be fixed when Lock View removes some code that is currently broken, as reported in CDeenen/LockView#61

My testing here, when the broken line is removed shows that Lock View works as expected in combination with Stream View, so going to close this out here - follow along on the Lock View issue to see this resolved.
