### ISSUE TITLE
No login window when adding OBS Browser

### ISSUE THREAD

**Issue by krusty4president** [sPOiDar/fvtt-module-stream-view#11]
Hi. Trying this module, following the instructions.
In OBS adding a "browser source" no login window appears, only the Foundry background body image. Not working with or without the /join in the URL.

**Comment by krusty4president** [comment]
![2021-11-16_17-26-37](https://user-images.githubusercontent.com/9943749/142025025-02e757fe-1593-4541-a48a-5fd5ba8293d6.jpg)

**Comment by sPOiDar** [comment]
Needs OBS on Windows to fix their browser source for Foundry to work.

https://github.com/sPOiDar/fvtt-module-stream-view/issues/6#issuecomment-908757433
