### ISSUE TITLE
Additional toggles on Stream View toolbar

### ISSUE THREAD

**Issue by janmarcano** [sPOiDar/fvtt-module-stream-view#12]
I think adding some additional toggles on the Stream View toolbar that change the visibility of certain visual elements for the Stream user would be useful.
The two use cases that come to mind are:
- Foreground Layer: useful to toggle roofs or overlays
- Journal Notes: change how much detail is shown on an overworld map

**Comment by sPOiDar** [comment]
There was some funky stuff to handle both of these:
- The foreground layer active state is not reported correctly for non-GM users - had to make the test also check for the alpha value to make this work properly (issue reported upstream).
- Notes don't show up unless you switch to/from the notes layer when toggling the value

In any case, these are implemented now.

**Comment by janmarcano** [comment]
thank you so much!
