### ISSUE TITLE
Set screen dead zone

### ISSUE THREAD

**Issue by BrotherSharper** [sPOiDar/fvtt-module-stream-view#14]
Normally the guided camera calculates it so all the players are shown on the screen.
However, some UI elements might appear at the top or bottom depending on what modules the streamer has enabled (combat tracker/carousel for example)
It would be beneficial that when the camera calculates where to focus we could set a dead zone, say 500 pixels off the top or bottom for the camera to consider the end of the screen in terms of calculating which portion it should show.

**Comment by sPOiDar** [comment]
Hi @BrotherSharper thanks for the suggestions, have you tried the existing camera padding options? There are separate settings available for standard and in-combat padding, which should support this use-case. Closing for now, but if these settings don't do what you need them to, please feel free to re-open and let me know what more is required.
