### ISSUE TITLE
Inline rolls not displayed

### ISSUE THREAD

**Issue by Rothmaw** [sPOiDar/fvtt-module-stream-view#15]
Inline rolls are not being displayed in the stream view chat. Example attached.

![image](https://user-images.githubusercontent.com/11473412/148108993-61f9d2e6-4701-4ee3-8a23-d5eae1f04e9c.png)

**Comment by sPOiDar** [comment]
All rolls work fine here.

Stream View does not do anything to the contents of the chat log, all it does is popout the chat and hide the controls (the input box, etc).

I'd suggest you try without any other modules enabled, to try and find what's causing this (or make sure that's not a private roll, though it doesn't look like it is). Also check the error console (hit F12) to see if there are any errors - that will help track down the source of the problem.

If you can reproduce this with no other modules enabled, and your other players can also see the roll, feel free to re-open, but I can't see how Stream View might cause this.
