### ISSUE TITLE
Add exception to popout auto-close for `Party Overview` module

### ISSUE THREAD

**Issue by sPOiDar** [sPOiDar/fvtt-module-stream-view#18]
Reported by `gumbo` on Discord.

**Comment by CasualTerror** [comment]
Also, it would be nice for Simple Calendar not too auto-close too.

**Comment by sPOiDar** [comment]
Fixed in the latest release. Simple Calendar uses mimimized code, so I had to match on a CSS class, might be a bit brittle.
