### ISSUE TITLE
Foundry web interface

### ISSUE THREAD

**Issue by onidemoni** [sPOiDar/fvtt-module-stream-view#19]
Sorry but i couldnt figure out where the foundry web interface is that you have to link in the browser source?
Neither the foundry discord or google helped me out with that one. 
Probably a dumb mistake on my part, but hopefully someone can enlighten me

**Comment by sPOiDar** [comment]
If you're running Foundry locally, it'll be http://localhost:30000 or if you're hosting somewhere, it'll be whatever URL you and your players use to connect to your game from your browser.

**Comment by onidemoni** [comment]
I self host, but even when i insert http://localhost:30000/ into the browser source it does not show anything. its just transparent. 
does it matter that i use streamlabs obs instead of just the standart obs?

**Comment by sPOiDar** [comment]
I take it that works from you browser? OBS on Windows only very recently upgraded to a version of chrome for the browser source that works with Foundry, slobs is probably running some ancient OBS version. So, if it doesn't work you'll probably have to capture a browser window, which is a little annoying but should work.
