### ISSUE TITLE
Hide Module UI

### ISSUE THREAD

**Issue by brunocalado** [sPOiDar/fvtt-module-stream-view#20]
Hi.

Can you add a way to hide UI from other modules?

In this case Ready to use cards and small time modules.
![image](https://user-images.githubusercontent.com/4999783/171931853-489a881d-e175-4789-aec9-9438610df3a8.png)

Tks

**Comment by sPOiDar** [comment]
I'm not sure there's a nice way to expose this functionality to users, since there are a whole host of different ways that modules can render their content. My first thought would be to allow users to specify CSS selectors for HTML elements to hide, but that would require users to have technical knowledge.

I'll have a think about it, but can't promise anything immediately.

**Comment by brunocalado** [comment]
GM Screen also add stuff.
![image](https://user-images.githubusercontent.com/4999783/172073237-40743b54-8c54-4d8f-a6ef-d4ca3cdfb8ac.png)

The share-media dev fixed for his module. He created a user blacklist. I add the stream user in the black list and it will not show.

**Comment by brunocalado** [comment]
> All three of those modules can be turned off and hidden in their own module settings.

To turn off the small time, I need to remove the stream user so, I can access settings. After that, I need to turn the stream user on again. OBS don't save this.

**Comment by CasualTerror** [comment]
> > All three of those modules can be turned off and hidden in their own module settings.
> 
> To turn off the small time, I need to remove the stream user so, I can access settings. After that, I need to turn the stream user on again. OBS don't save this.

It should. Mine does.

**Comment by AxiumDND** [comment]
You can force stream view to show full sidebar then in OBS you can go in and turn off those settings. then turn off show full side bar refresh and then your good to go.

**Comment by brunocalado** [comment]
Thank you all.
