### ISSUE TITLE
Compatibility Request: Levels Module

### ISSUE THREAD

**Issue by unrealkakeman89** [sPOiDar/fvtt-module-stream-view#21]
I would like to request compatibility with the Levels Module. 
Currently, when using Stream View and Levels, it does follow the player during combat, however, it shows only the uppermost level and all of the tiles from the levels below. 
It would be ideal if it would use the Tokens vision to see only the level the token is on and only what the token can see. 
I, unfortunately, am not familiar enough with programming to be of assistance, I am just able to make the request.

**Comment by sPOiDar** [comment]
This is not something that can be fixed here - this module simply relies on the Observer permission built-in to core Foundry to share vision.

It sounds like the Levels module does not work well when other players have Observer vision, and any changes in that behaviour would have to happen inside the Levels module, so I'd suggest you place a feature request over there.

**Comment by sPOiDar** [comment]
Stream View doesn't really focus a specific token, it just adjusts the camera bounds to keep tokens in view (in automatic mode, in directed mode, tokens aren't considered at all). That said, this is not just a problem for Stream View, but for any game where players want shared party vision.

IMO if Levels wanted to properly support observers or multiple owners, it would push updates to players that have vision perms for the token when the token's elevation changes.

**Comment by theripper93** [comment]
Well, then I guess compat is not really possible , if I have some extra time I might do something as you suggest
