### ISSUE TITLE
stream view and levels

### ISSUE THREAD

**Issue by slyandsmart** [sPOiDar/fvtt-module-stream-view#25]
Hi i use froundry 9 (269) as well as levels 2.8.9.2 and stramview 0.4.4.
But i can not see the any token on a deeper level inside the stream view browser.

Hope you can help me with this. 

Kind regards sly

**Comment by sPOiDar** [comment]
Duplicate of #21 

Levels does not support Foundry observers, so Stream View can't support it. The Levels author theripper93 said they might consider fixing this at some point.
