### ISSUE TITLE
[Feature request] Controls for the Size of Journals or artwork pop outs.

### ISSUE THREAD

**Issue by AxiumDND** [sPOiDar/fvtt-module-stream-view#28]
Hi there use stream view all the time works great and been happy with it. As always thanks for all the hard work on this.

One feature I have been wondering if its possible. on my stream I have overlay that covers portions of the foundry screen It would be handy if I could change the position and the size of journal popouts or artwork being shown so the stay in a portion of the screen I set.

Thanks again

Axium

**Comment by sPOiDar** [comment]
Should be doable. Would a single size/pos for all popouts work, so they all appear at the same location? Would mean multiple popouts would overlap, stacked directly on top of each other, but otherwise things would get kind of complicated.

**Comment by AxiumDND** [comment]
That wouldnt be an issue at all would fit my needs. Thanks

**Comment by sPOiDar** [comment]
Available in v1.2.0

**Comment by AxiumDND** [comment]
This Works perfectly Thankyou so much for putting in the work on this.
