### ISSUE TITLE
[Feature Request] Camera: Add Disable Combatant Tracking Option

### ISSUE THREAD

**Issue by bryancasler** [sPOiDar/fvtt-module-stream-view#31]
I'd like a Camera Mode to follow a specific token both in and out of combat.

My use case is that I'm using Stream View for an in person game with a TV as the combat map and physical mini's on the screen, but digital counterparts in Foundry for the purpose of tracking Combat and NPC HP/resources. The challenge I am running into right now is when combat starts. Every time the underlying digital map moves all the physical minis need to get moved which is not ideal. The "Camera Mode: Directed" is also not an option, I need the freedom to move my DM view without affecting the digital battle map view on the TV.

As an alternative to "Follow X Token" it could also be a way to disable the auto following of tokens during combat when "Camera Mode: Automatic" is used.

I know this is niche and would be happy to sponsor this development for v9, just let me know how I can help out.

**Comment by sPOiDar** [comment]
I'm sorry to say that with the changes in v10, I'm not able to support v9 for new development. On a happier note, following specific tokens is a feature I've just added in the most recent version (for v10). It does not currently continue tracking when combat starts, but that would be a simple option to add.

**Comment by sPOiDar** [comment]
Available in v1.2.0

**Comment by bryancasler** [comment]
Wow, that's incredible. Thank you so much. I can't move to v10 just yet but should be able to do soon. Can't wait to try this out.

**Comment by bryancasler** [comment]
Just wanted to let you know I was finally able to move to v10 and it's working great. The camera no longer moves when the combatant changes.
