### ISSUE TITLE
Compatibility with v10.286

### ISSUE THREAD

**Issue by TheSmilingDM** [sPOiDar/fvtt-module-stream-view#35]
Foundry is reporting Cannot be enabled due to issues in required dependencies. I figure this is a problem with libWrapper as that is the only dependency reporting an issue in the console. Just wondering if there is any current workaround for this at all?
libWrapper is on v1.12.5.0
socketlib is on v1.0.11
Stream View is on v1.2.0

**Comment by sPOiDar** [comment]
The latest version of libWrapper is v1.12.10.0, you'll need to work out why you're not seeing that. If you can't work it out, the Foundry Discord is probably the best place to follow up.
