### ISSUE TITLE
When I move to another scene!

### ISSUE THREAD

**Issue by BoTKaPyC** [sPOiDar/fvtt-module-stream-view#36]
when I go to the scene, I throw out a bunch of errors. Please tell me how to solve this?
![1](https://user-images.githubusercontent.com/80960291/193565324-e6b3caa2-c6ea-4ec6-96f9-91f4f266712a.png)

**Comment by sPOiDar** [comment]
Thanks for the report, and apologies for the trouble - should be fixed in the latest version, let me know if you have any issues.
