### ISSUE TITLE
Macro Request

### ISSUE THREAD

**Issue by ChobitsCrazy** [sPOiDar/fvtt-module-stream-view#37]
Not sure if it's possible but would be cool to have a macro that can toggle between Automatic and Directed views for the DM.

**Comment by elemorelli** [comment]
Piggybacking on this enhancement request!

Having a way to toggle the modes directly the hotbar would be amazing.

**Comment by sPOiDar** [comment]
Added a macros compendium, please try them out in the latest release.

**Comment by elemorelli** [comment]
Seems to work flawlessly! Thanks!
