### ISSUE TITLE
Combat Tracker not showing up

### ISSUE THREAD

**Issue by Vorkane** [sPOiDar/fvtt-module-stream-view#4]
I am able to view chat, and everything else works (following PCs with Stream user as observer). But the Combat Track will not show up. I have created a new world and even tried on it still same thing. I am not seeing any errors in either the "GM" session or the "Player" session as to why. 

Is there anything else I can test to verify if it's something on my end?

**Comment by sPOiDar** [comment]
The combat tracker for the stream view only appears when combat is active (i.e after you click `Begin Combat`). If it is still not appearing, can you log in as the stream user in a browser and check the Javascript console? Everything appears to be working as it should here.

**Comment by Vorkane** [comment]
Hmm, it was not working before. I have done a reset to defaults in the Module Settings. That seemed to clear up the issue. Sorry for the false alarm.

**Comment by sPOiDar** [comment]
FYI, this was a bug, when using `Directed` camera mode, it should be fixed in the latest version.
