### ISSUE TITLE
Directed mode only follows camera movements on the activated scene.

### ISSUE THREAD

**Issue by cs96and** [sPOiDar/fvtt-module-stream-view#42]
Stream View only seems to follow canvas movements on the activated scene. E.g.

1. Activate scene 1
2. As GM move to Scene 2 (but don't activate it)
3. Pull stream user to scene 2
4. Move the camera around. No changes are made to the stream user's view
5. As GM, move back to scene 1
6. Move the camera around. The camera moves on the stream user's view

**Comment by sPOiDar** [comment]
This should work as expected in the latest release.
