### ISSUE TITLE
Dark Vision Bug?

### ISSUE THREAD

**Issue by KirikTheOrc** [sPOiDar/fvtt-module-stream-view#47]
When viewing a scene with Token Vision on, Has Inverted Colors 
![Screenshot 2022-11-24 193108](https://user-images.githubusercontent.com/53062657/203896196-838120e2-9381-48d0-aeaa-6f8165373d39.png)

**Comment by sPOiDar** [comment]
Core FoundryVTT bug related to multiple tokens and darkvision, think it's meant to be fixed in the next release: https://github.com/foundryvtt/foundryvtt/issues/8507

**Comment by KirikTheOrc** [comment]
Thank you!
