### ISSUE TITLE
[Feature Request] Camera: Disable Token Movement Tracking

### ISSUE THREAD

**Issue by bryancasler** [sPOiDar/fvtt-module-stream-view#49]
Similar to my last request on #31 I am using Stream View for an in person game with a TV as the combat map and physical mini's on the screen, but digital counterparts in Foundry for the purpose of tracking Combat and NPC HP/resources. The challenge I am running into right now is that when using the Automatic camera mode, and a token moves, the underlying digital map moves to focus on that token and all the physical minis need to get moved. The "Camera Mode: Directed" is also not an option, I need the freedom to move my DM view without affecting the digital battle map view on the TV.

I don't know if the best answer to this is another checkbox, or a new camera mode, something like "Stationary" where the camera does not move except by direct interaction from the user to pan/zoom the background.

Similar to my last request, I know this is niche and would be happy to sponsor this development. Just let me know how I can help out.

**Comment by sPOiDar** [comment]
There's a new `Disabled` camera mode in the latest version, please try it and see if it meets your needs.
