### ISSUE TITLE
Compatibility with Levels Module

### ISSUE THREAD

**Issue by darthlunga** [sPOiDar/fvtt-module-stream-view#50]
Hello! Thank you for this module; it is a game-changer for me! It works great, however, when I have maps that utilize the Levels module, it only displays the main Level (0-9) regardless of what elevation the tokens are at. Is this a known thing or am I missing a setting?

**Comment by sPOiDar** [comment]
Levels doesn't support Foundry observers, and so Stream View can't support Levels in its current state. The Levels author initially said they might consider improving things, but later I believe said that was unlikely to happen.

Duplicate of #21
