### ISSUE TITLE
Close pop-up doesn't work in another window

### ISSUE THREAD

**Issue by Stotorm** [sPOiDar/fvtt-module-stream-view#54]
Hey, i noticed that the button Close Pop-Up dosn't work when i use Streamviewer in another chrome windows (wich is in private mode, loggin reason). Is there something you can do about this ?
Thanks for you module ! It help a lot for my content !

**Comment by sPOiDar** [comment]
This is working fine for me. Are there any errors in the Chrome console (F12) on either the GM or Stream side? Does it happen with no other modules enabled?

**Comment by Stotorm** [comment]
Hey, sorry for late response, not so much time for computer those times.
So, there is no error on Chrome console in either Gm or Stream Windows.
I desabled all modules :(

**Comment by sPOiDar** [comment]
What version of Foundry and Stream View are you using?

**Comment by Stotorm** [comment]
The latest. Everything is up to date

**Comment by sPOiDar** [comment]
I still cannot reproduce this problem, just to confirm - this feature only manages popouts that are created by e.g. showing handouts to players, it won't close all windows on that stream view, for example the chat log, or windows created by other plugins, is that what you were trying to do?

**Comment by sPOiDar** [comment]
Closing due to lack of response/details, please feel free to re-open if you have more context.
