### ISSUE TITLE
Firefox issue.

### ISSUE THREAD

**Issue by MythicalRollers** [sPOiDar/fvtt-module-stream-view#56]
I host multiple worlds in my CoS world I use Stream View 1.3.0 and do not have any issues.  I use chrome for my screen and Firefox for the Stream View screen.
In my Rime world I upgraded to 1.6.2 and my stream view Firefox browser gets this error:
Error: Error thrown in hooked function '' for hook 'renderCameraViews'. This is not a registered game setting
[Detected 3 packages: lib-wrapper, force-client-settings, stream-view]

**Comment by sPOiDar** [comment]
Thanks for reporting, and apologies for the bug, should be resolved in the latest version.
