### ISSUE TITLE
[Feature Request] Option to set Combat Tracker Height

### ISSUE THREAD

**Issue by King-Wedgie** [sPOiDar/fvtt-module-stream-view#57]
Just looking for the same as Chat Maximum Height, really. I'd like to have chat and the tracker on the same side of the screen without overlapping due to the number of combatants:
![image](https://user-images.githubusercontent.com/73143074/236692262-57b32a87-2b76-40c0-9c28-2a771f2b7595.png)

Related, maybe add a function for chat height during combat, like what's implemented for the camera padding. Only issue with this is that currently I have to refresh the page whenever I edit its size or position; no idea if you can just refresh the chat.

**Comment by sPOiDar** [comment]
Included in v1.7.0, let me know if you run into any issues.

**Comment by King-Wedgie** [comment]
Works great! There is one slight issue; the combat tracker Y position doesn't account for non default heights, as seen below:
![image](https://github.com/sPOiDar/fvtt-module-stream-view/assets/73143074/af4410f0-374e-4764-bdb3-c17b79ebc3f2)
(same result if set to a high positive number)

**Comment by sPOiDar** [comment]
I see what the problem is, will try to find some time this week to sort it out.

**Comment by sPOiDar** [comment]
Please try v1.7.1

**Comment by King-Wedgie** [comment]
Seems to be working perfectly! I realized after the previous post that the tracker was being positioned based on how many combatants were in combat, so it looks like that's been corrected. Thanks so much!
