### ISSUE TITLE
LiveKit: No camera selected causes issue.

### ISSUE THREAD

**Issue by MythicalRollers** [sPOiDar/fvtt-module-stream-view#62]
I know this says Live kit but if I disable Stream View it works.  If the "Stream" account does not have a camera selected, then the below error populates for Firefox.

LiveKitAVClient | Could not connect: Error: could not establish pc connection
    tr livekit-client.esm.mjs:13569
    ir livekit-client.esm.mjs:13575
    a livekit-client.esm.mjs:21878
[LiveKitAVClient.ts:351:16](webpack://avclient-livekit/src/LiveKitAVClient.ts)
Error connecting to LiveKit Server: could not establish pc connection [foundry.js:59187:78]

**Comment by MythicalRollers** [comment]
If I disable stream view, set a camera onto the account instead of "default" then reenable the Stream View. then it works again, though slowly.

**Comment by sPOiDar** [comment]
Does the same error occur for any other player if they do not have a camera selected?

**Comment by MythicalRollers** [comment]
I have a game tonight and will test this with a player.

**Comment by MythicalRollers** [comment]
Clearing the cache in Firefox fixed it.  Closing ticket.
