### ISSUE TITLE
[bug] "Chat Maximum Height (combat)" is being ignored

### ISSUE THREAD

**Issue by King-Wedgie** [sPOiDar/fvtt-module-stream-view#63]
**FoundryVTT** v10.291
**Stream View** v1.7.1

As title; chat just uses the non-combat height regardless of combat state.

**Comment by sPOiDar** [comment]
Hmm, I can't reproduce here - the height updates as expected when I begin/end combat here. Try a hard refresh, either by shift-refresh in a browser, or `Refresh cache of current page` in OBS browser source, since the new min-height overrides rely on the CSS file for the module.

**Comment by King-Wedgie** [comment]
Okay, so after some more testing, it's definitely something funky with using the default height. 

To replicate:
1) Start an instance as normal, with a separate browser logged in as the Stream View.
2) Under Stream View settings, set "Chat Maximum Height" (non-combat) to 0 or negative to enable the default height, and set the combat height to anything else for differentiation purposes
3) Refresh the Stream View browser to apply changes, and on the main browser, begin an encounter (or go to the next/previous turn/round if an encounter is already running).
4) Profit.

To "fix":
1) Same as above.
2) Same as above, except set non-combat height to a high number.
3) Same as above.
4) Profit.

I can also confirm that it doesn't appear to be a conflict with a specific system or module; HOWEVER, in DnD5e v2.2.1, I'm unable to set a user as the Stream View (the dropdown doesn't populate), so that might be a new issue (I've been running in PF2E these days).

**Comment by sPOiDar** [comment]
Just to confirm that I understand, you're saying that if the non-combat size is auto, the configured in-combat size is ignored during combat? I'll take a look, it's possible I missed this setup during my testing.

As for the user selection issue, does your dnd5e test world have any non-GM users available? The list does not include GMs.

**Comment by King-Wedgie** [comment]
1) Yes, that seems to be what's happening.

2) Yeah, I have 3 users set at the Player level.

**Comment by sPOiDar** [comment]
1. For some reason Foundry checks whether the app window was originally created with `auto` height, and deletes any height provided when attempting to set the size/position of the window forever after. Fix incoming, but I may report this as a bug against core.
2. I cannot reproduce this - dnd5e v2.2.1 on both Foundry v10.291 and v11.299 populates the user list as expected, this should probably move to a new issue though if you're able to reproduce it reliably (perhaps try a new test world to see if it's something world-specific).

**Comment by King-Wedgie** [comment]
1) Sweet. Can confirm the fix works.

2) Yeah, I can't seem to reproduce the issue. I ended up safe mode-ing the world and that appears to have cleared up whatever the issue was. 🤷
