### ISSUE TITLE
Showing the GM selected token's vision

### ISSUE THREAD

**Issue by mumrah** [sPOiDar/fvtt-module-stream-view#65]
I am getting things situated with FoundryVTT for an in-person game. I would like the ability for the GM to select a token, and for that token's vision to be shown by the Stream View UI. Currently, it seems like all the vision circles for the tokens being observed by the stream user are shown. 

For example, in the following screenshot, the token on the left is selected in the GM view, but in the Stream view the vision for the token on the right is visible. 
![image](https://github.com/sPOiDar/fvtt-module-stream-view/assets/55116/6e714c73-f9fe-4231-98c2-15e78bd97950)

This would help me easily convey what an individual player's token can see without interacting with the stream UI. Ideally, I'll just setup a TV to display the stream user's view and not have to touch it for the rest of the session. Basically, I want to fully control what I see as the GM and what my players see, but only using the GM's UI.

There was a brief discussion in the FoundryVTT discord here https://discord.com/channels/170995199584108546/494726439263010826/1116134105009102930

This is a feature that I got used to when using EncounterPlus on my Mac.

**Comment by sPOiDar** [comment]
Please try the new `Track GM Controlled Tokens` option in v1.8.0

**Comment by sPOiDar** [comment]
Great, happy games and if you have any issue LMK.
