### ISSUE TITLE
Computability issue.

### ISSUE THREAD

**Issue by MythicalRollers** [sPOiDar/fvtt-module-stream-view#66]
**Describe the bug**
Version 2.0 does not seem to be compatible with V10, even though it allows me to upgrade to it.

**To Reproduce**
In a V10 world with no history of Stream View being setup, install Stream View from the addons menu.
Log into your world and enable Stream View
Try to set an account as the "Viewer", notice no accounts are listed to be the "Viewer".

**Expected behavior**
I expected one of 12 accounts to be listed.

**Screenshots**
<img width="587" alt="image" src="https://github.com/sPOiDar/fvtt-module-stream-view/assets/106455111/3b38800f-c7ee-4ead-9909-08068b02965b">

**Checklist**
- [X] Tested with all other modules disabled

**Environment (please complete the following information)**
 - FoundryVTT Version: [e.g. v10]
 - Stream View Version: [e.g. v2.0]
 - Browser: [e.g. Chrome]

**Additional context**
Downgrading back to 1.6.3 resolves this account issue for V10.

**Comment by sPOiDar** [comment]
Apologies, looks like Foundry v10 initializes users very late compared to v11, please try Stream View v2.0.1
