### ISSUE TITLE
Transmit playlist audio

### ISSUE THREAD

**Issue by ZeroIchiro** [sPOiDar/fvtt-module-stream-view#68]
Maybe I am just too stupid (again), but it seems that when I add the Stream View browser source to OBS, music that is played is not transmitted, at least I see no audio level for this in OBS.
Is this intentional? And if so, could this be added as an optional function?

**Comment by sPOiDar** [comment]
Stream View doesn't do anything special with music/audio. After logging in, you may need to Interact with the browser source and click the canvas once to activate audio - this is a browser limitation, same thing is required for your players.
