### ISSUE TITLE
Camera keeps trying to follow a talking player, even though I have that option unticked?

### ISSUE THREAD

**Issue by nirurin** [sPOiDar/fvtt-module-stream-view#7]
As title. I'm in automatic mode, but have unticked the option to follow a talking player, but the camera keeps doing it anyway. I have tried to minimise the issues by making the delay really long, but its still causing problems.

**Comment by sPOiDar** [comment]
Should be fixed by 14db2ce in v0.2.2

Feel free to update here if you're still seeing any undesired behaviour with that setting disabled.
