### ISSUE TITLE
[bug] Issue with Toggle Camera Buttons

### ISSUE THREAD

**Issue by Oryan77** [sPOiDar/fvtt-module-stream-view#71]
The toggle camera buttons don't seem to work as I would expect. A screenshot of my settings shows my configuration.

**Outside of combat**, the Toggle Camera Mode button works correctly when in Director mode (the Stream follows the GM view). When the Toggle Camera Mode button is disabled (set to Automatic), it does not follow the view (zoom/pan) of the player that owns the tracked token. It tracks the token, but does not zoom/pan when the player zoom/pans. I don't see a way to swap between following the player view (zoom/pan) and not following the player view while tracking.

**During combat**, neither of the Toggle Camera buttons work. I understand that checking "Directed Combat" in settings might disable these buttons during combat, so this could be by design. But, there may be certain situations where the GM might need to temporarily change how the Stream View player is working.

For example, when there is a player owned token on the map, but the player is not logged in, Stream View does not follow the view (zoom/pan) of the GM when he needs to control the player token. I assume that the Toggle Camera buttons exist for exactly this reason (emergency/temporary tracking/camera changes).

Perhaps this is not actually a bug and more of a feature request?

I do have an mp4 of my screens showing that the two Toggle Camera buttons don't work at all during combat. It's a 60+ mb file and I figured I would only upload it if you need it.

 - FoundryVTT Version: v11.307]
 - Stream View Version: [e.g. v2.0.2]
 - Browser: [e.g. Chrome & Firefix]
 - Capture Mode (if applicable): [OBS Studio Browser Source]

![image](https://github.com/sPOiDar/fvtt-module-stream-view/assets/49130820/4ee16932-5502-4fd6-bec8-6ec6c11d2dd1)

**Comment by sPOiDar** [comment]
> When the Toggle Camera Mode button is disabled (set to Automatic), it does not follow the view (zoom/pan) of the player that owns the tracked token. It tracks the token, but does not zoom/pan when the player zoom/pans. I don't see a way to swap between following the player view (zoom/pan) and not following the player view while tracking.

Right, tracking a token doesn't replicate the token owner's view (multiple tokens may be tracked, so I'm not really sure how this would work), it simply limits auto-tracking to following the tracked token(s) instead of the whole party.

> During combat, neither of the Toggle Camera buttons work. I understand that checking "Directed Combat" in settings might disable these buttons during combat, so this could be by design. But, there may be certain situations where the GM might need to temporarily change how the Stream View player is working.
>
> For example, when there is a player owned token on the map, but the player is not logged in, Stream View does not follow the view (zoom/pan) of the GM when he needs to control the player token. I assume that the Toggle Camera buttons exist for exactly this reason (emergency/temporary tracking/camera changes).

This behaviour was changed in the latest version due to a user report that GM directed camera movement was interferring with player camera movement during combat when Directed Combat was enabled. I suppose we could add a check to see if any token owners are online, and default to auto/GM-control if they're not, which would solve the scenario you've described.

**Comment by sPOiDar** [comment]
In the v2.0.3 release I've added logic to track the GM camera during combat if the current combatant's player owner is not active, when Directed Combat is enabled.

Please let me know if you have any issues.
