### ISSUE TITLE
[feat] Additional Modes: Track Party & Full Screen

### ISSUE THREAD

**Issue by Oryan77** [sPOiDar/fvtt-module-stream-view#72]
Monk's Common Display has has these two features which seems quite useful.

**Track Party** will zoom the Stream View out enough to see every player token located on the same map. If the player tokens move closer together, the Stream View zooms in enough to still keep them all in view.

**Full Screen** simply zooms the Stream View out to the size of the entire map and stays locked in that position.

**Comment by sPOiDar** [comment]
I'm going to close this one out as I believe this is covered by existing functionality, feel free to comment if I've misunderstood.
