### ISSUE TITLE
Directed camera still follows on a different scene

### ISSUE THREAD

**Issue by janmarcano** [sPOiDar/fvtt-module-stream-view#9]
While using directed camera, switching to another scene without activating it makes the camera follow to the coordinates on the new scene, but the streaming player is still on the active map and shows the wrong place.

This can be troublesome if I want to check something before moving the players there, since if I switch to Automatic before switching, I lose my previous camera position as well.

Maybe a toggle to pause the camera could be added to the Streaming Toolbar?
Otherwise make it so Directed camera doesn't follow the GM view when he is somewhere else?

EDIT: Sorry for the half-assed issue at first, submitted it incomplete by accident

**Comment by sPOiDar** [comment]
I think the pause button might be a little difficult to manage, but I think your idea of not tracking when the GM is on a scene that's not active makes a lot of sense, I'll try to find a little time to implement this in the near future.

**Comment by janmarcano** [comment]
thank you so much for taking it into consideration!

**Comment by sPOiDar** [comment]
This feature should be available in v0.3.0, please let me know if you encounter any issues.

**Comment by funwithfondue** [comment]
Works fine! Thanks a lot!
